In [1]:
import pickle
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [3]:
dictBatch1 = unpickle('cifar-10-batches-py/data_batch_1')

In [155]:
#tipos de dados que vem do data_batch_1
dataBatch1 = []
dataBatch1 = dictBatch1[b'data']
print(dataBatch1)
#print(dictBatch1)
#print(dictBatch1[b'batch_label'])
#print(dictBatch1[b'labels'])
#print(dictBatch1[b'data'])
#print(dictBatch1[b'filenames'])

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 71  60  74 ...  68  69  68]
 [250 254 211 ... 215 255 254]
 [ 62  61  60 ... 130 130 131]]


In [256]:
def RGBchannels(ar, out):
    
    
    lines = 2
    
    Rchannel = list(range(0,1024))
    Gchannel = list(range(0,1024))
    Bchannel = list(range(0,1024))
    
    outTest = []
    
    begin = 0
    end = 3072
    i = 0
    
    while (i < lines):
        while (begin < end):

            if (begin < 1024):
                #print(begin)
                Rchannel[begin] = (ar[i][begin])
            elif (begin < 2048):
                Gchannel[begin - 1024] = (ar[i][begin])
            elif (begin < 3072):
                Bchannel[begin - 2048] = (ar[i][begin])
              
            if (begin == 1023):
                out[i] = Rchannel
                #print(Rchannel)
                
            begin += 1
            
        print(Rchannel[2])

        begin = 0
        i += 1
        
    return out

In [257]:

out = list(range(0,2))
out = RGBchannels(dataBatch1, out)

#print(out[0])
#print(Rarray[0][0])

50
105


In [323]:
def RGB(ar):
    
    Rlist = []
    Glist = []
    Blist = []
    lines = 2
    
    arList = ar.tolist()
    
    #R
    for i in range(0, lines):
        Rlist.append(arList[i][0:1024])
    #G
    for i in range(0, lines):
        Glist.append(arList[i][1024:2048])
    #B
    for i in range(0, lines):
        Blist.append(arList[i][2048:3072])
        
    return Rlist, Glist, Blist

In [338]:
Rlist, Glist, Blist = RGB(dataBatch1)

print(dataBatch1[0][2048])

print(Blist[0][0])

63
63
